"""grupos de chat (canais)

Revision ID: 20a93fcc58c2
Revises: f5562750bb49
Create Date: 2026-07-18 17:16:28.278970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a93fcc58c2'
down_revision = 'f5562750bb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('icone', sa.String(length=40), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_chat_membros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_chat.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'user_id', name='uq_grupo_membro')
    )
    with op.batch_alter_table('grupos_chat_membros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grupos_chat_membros_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grupos_chat_membros_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grupo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_mensagens_grupo_id'), ['grupo_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_mensagens_grupo_id_grupos_chat', 'grupos_chat', ['grupo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_mensagens_grupo_id_grupos_chat', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_mensagens_grupo_id'))
        batch_op.drop_column('grupo_id')

    with op.batch_alter_table('grupos_chat_membros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grupos_chat_membros_user_id'))
        batch_op.drop_index(batch_op.f('ix_grupos_chat_membros_grupo_id'))

    op.drop_table('grupos_chat_membros')
    op.drop_table('grupos_chat')
    # ### end Alembic commands ###
