"""landing page: configuracao_site

Revision ID: 36dd6e110058
Revises: 41aaa4332a20
Create Date: 2026-07-16 03:14:46.129118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dd6e110058'
down_revision = '41aaa4332a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_empresa', sa.String(length=120), nullable=False),
    sa.Column('slogan', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_fundo', sa.Enum('nenhum', 'imagem', 'video', name='tipofundo'), nullable=False),
    sa.Column('imagem_fundo_url', sa.String(length=255), nullable=True),
    sa.Column('video_fundo_url', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('cor_destaque', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao_site')
    # Ver comentário equivalente em 8d718f98e6c1: drop_table não dropa o
    # tipo ENUM sozinho no Postgres.
    sa.Enum(name='tipofundo').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
