"""usuarios com aprovacao (role/status) e chat interno

Revision ID: 41aaa4332a20
Revises: 8d718f98e6c1
Create Date: 2026-07-15 11:08:12.512034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aaa4332a20'
down_revision = '8d718f98e6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('editado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_mensagens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_mensagens_user_id'), ['user_id'], unique=False)

    # No PostgreSQL, um `add_column` com sa.Enum NÃO cria o tipo
    # automaticamente (isso só acontece de graça quando o Enum nasce
    # junto com um `create_table`). Sem este passo explícito, a produção
    # (Postgres) falha com "type roleusuario does not exist" logo na
    # primeira subida, mesmo que tudo funcione normalmente em SQLite (que
    # não tem tipo enum nativo — guarda como texto). checkfirst=True torna
    # isso seguro de rodar de novo (idempotente).
    bind = op.get_bind()
    sa.Enum('admin', 'usuario', name='roleusuario').create(bind, checkfirst=True)
    sa.Enum('pendente', 'aprovado', 'reprovado', name='statususuario').create(bind, checkfirst=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('admin', 'usuario', name='roleusuario'), nullable=False, server_default='usuario'))
        batch_op.add_column(sa.Column('status', sa.Enum('pendente', 'aprovado', 'reprovado', name='statususuario'), nullable=False, server_default='pendente'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_mensagens_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_mensagens_created_at'))

    op.drop_table('chat_mensagens')

    bind = op.get_bind()
    sa.Enum(name='roleusuario').drop(bind, checkfirst=True)
    sa.Enum(name='statususuario').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
