"""imagem nos avisos e configuracao de personalizacao dos cards

Revision ID: 5a1530c21d45
Revises: 9d286873883b
Create Date: 2026-07-17 08:15:19.370031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1530c21d45'
down_revision = '9d286873883b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotulos', sa.JSON(), nullable=False),
    sa.Column('estilo', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    op.drop_table('configuracao_cards')
    # ### end Alembic commands ###
