"""modelos iniciais: users, cidades, avisos

Revision ID: 8d718f98e6c1
Revises: 
Create Date: 2026-07-14 19:05:08.811877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d718f98e6c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=160), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('modo_duracao', sa.Enum('dias', 'horas', name='mododuracaoaviso'), nullable=False),
    sa.Column('inicio', sa.String(length=20), nullable=False),
    sa.Column('fim', sa.String(length=20), nullable=True),
    sa.Column('duracao_horas', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('perfil', sa.Enum('matriz', 'filial', name='perfilcidade'), nullable=False),
    sa.Column('modo_prazo', sa.Enum('periodo', 'dataHora', 'semData', name='modoprazo'), nullable=False),
    sa.Column('prazo_inicio', sa.String(length=20), nullable=True),
    sa.Column('prazo_fim', sa.String(length=20), nullable=True),
    sa.Column('regra_horas', sa.String(length=255), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('tecnicos_fim_semana', sa.Boolean(), nullable=False),
    sa.Column('tipo_abertura_fim_semana', sa.Enum('normal', 'emergencia', 'fechado', name='tipoaberturafds'), nullable=False),
    sa.Column('plantonista_fds', sa.String(length=120), nullable=True),
    sa.Column('modo_auto_plantonista', sa.Boolean(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cidades_nome'), ['nome'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cidades_nome'))

    op.drop_table('cidades')
    op.drop_table('avisos')

    # No PostgreSQL, dropar a tabela NÃO dropa os tipos ENUM associados a
    # ela — eles ficam órfãos no banco. Sem isso, reinstalar do zero (ex.:
    # `flask db downgrade base` seguido de `flask db upgrade` de novo, algo
    # comum em ambientes de teste/CI) falha com "type ... already exists".
    bind = op.get_bind()
    sa.Enum(name='mododuracaoaviso').drop(bind, checkfirst=True)
    sa.Enum(name='perfilcidade').drop(bind, checkfirst=True)
    sa.Enum(name='modoprazo').drop(bind, checkfirst=True)
    sa.Enum(name='tipoaberturafds').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
