"""perfil de usuario (nome, foto, tema) e avisos com autor e tipo

Revision ID: 9d286873883b
Revises: dac167158c05
Create Date: 2026-07-17 02:07:33.794594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d286873883b'
down_revision = 'dac167158c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - ajustado à mão: as colunas
    # novas são NOT NULL, então precisam de server_default para preencher
    # as linhas já existentes (o default do Python não se aplica a um
    # ALTER TABLE em linhas já gravadas).
    # Ver o comentário equivalente na migração 41aaa4332a20: em PostgreSQL,
    # `add_column` com sa.Enum não cria o tipo sozinho — precisa ser
    # criado explicitamente antes, ou a produção quebra na primeira subida
    # (SQLite não sofre disso por não ter tipo enum nativo).
    bind = op.get_bind()
    sa.Enum('informativo', 'atencao', 'urgente', name='tipoaviso').create(bind, checkfirst=True)
    sa.Enum('escuro', 'claro', name='temapreferencia').create(bind, checkfirst=True)

    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('informativo', 'atencao', 'urgente', name='tipoaviso'), nullable=False, server_default='informativo'))
        batch_op.add_column(sa.Column('autor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_avisos_autor_id'), ['autor_id'], unique=False)
        batch_op.create_foreign_key('fk_avisos_autor_id_users', 'users', ['autor_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('foto_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tema', sa.Enum('escuro', 'claro', name='temapreferencia'), nullable=False, server_default='escuro'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tema')
        batch_op.drop_column('foto_url')
        batch_op.drop_column('nome')

    with op.batch_alter_table('avisos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_avisos_autor_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_avisos_autor_id'))
        batch_op.drop_column('autor_id')
        batch_op.drop_column('tipo')

    bind = op.get_bind()
    sa.Enum(name='temapreferencia').drop(bind, checkfirst=True)
    sa.Enum(name='tipoaviso').drop(bind, checkfirst=True)
    # ### end Alembic commands ###
