"""sessoes_usuario: registro de sessao por dispositivo

Revision ID: dac167158c05
Revises: 36dd6e110058
Create Date: 2026-07-16 21:10:25.226326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac167158c05'
down_revision = '36dd6e110058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessoes_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessoes_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessoes_usuario_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessoes_usuario_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessoes_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessoes_usuario_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessoes_usuario_token'))

    op.drop_table('sessoes_usuario')
    # ### end Alembic commands ###
