"""mensagens privadas no chat (destinatario)

Revision ID: f5562750bb49
Revises: 5a1530c21d45
Create Date: 2026-07-17 22:29:44.796353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5562750bb49'
down_revision = '5a1530c21d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinatario_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_mensagens_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_mensagens_destinatario_id_users', 'users', ['destinatario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_mensagens_destinatario_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_mensagens_destinatario_id'))
        batch_op.drop_column('destinatario_id')

    # ### end Alembic commands ###
